{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 89,
   "id": "5c40eece",
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "import os\n",
    "import re\n",
    "from datetime import datetime\n",
    "from ollama import chat\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "id": "cfa00f6f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  patient_id  age     sex  fasting                         conditions  \\\n",
      "0    LAB_001   29  female     True                                 []   \n",
      "1    LAB_002   44    male    False                     [hypertension]   \n",
      "2    LAB_003   63    male     True  [type 2 diabetes, hyperlipidemia]   \n",
      "3    LAB_004   38  female     True                                 []   \n",
      "4    LAB_005   51  female     True                          [obesity]   \n",
      "\n",
      "                 medications              symptoms  labs.LDL  labs.HDL  \\\n",
      "0                         []             [fatigue]       118        62   \n",
      "1               [amlodipine]                    []       154        38   \n",
      "2  [metformin, atorvastatin]                    []        88        36   \n",
      "3                         []  [nausea, dark urine]       102        54   \n",
      "4                         []                    []       172        34   \n",
      "\n",
      "   labs.Triglycerides  labs.A1c  labs.Creatinine  labs.eGFR  labs.ALT  \\\n",
      "0                  92       5.2              0.8        104        20   \n",
      "1                 286       6.0              1.0         94        46   \n",
      "2                 248       8.1              1.5         52        28   \n",
      "3                 108       5.4              0.9         93       184   \n",
      "4                 342       6.7              1.1         68        96   \n",
      "\n",
      "   labs.AST  labs.Vitamin_D  \n",
      "0        19              16  \n",
      "1        34              24  \n",
      "2        24              27  \n",
      "3       162              31  \n",
      "4        82              18  \n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "import pandas as pd\n",
    "\n",
    "file_path = \"physician_copilot_student_cases.json\"\n",
    "\n",
    "with open(file_path, \"r\") as f:\n",
    "    data = json.load(f)\n",
    "\n",
    "df = pd.json_normalize(data)\n",
    "print(df.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "id": "e8c5dc21",
   "metadata": {},
   "outputs": [],
   "source": [
    "LAB_RULES = {\n",
    "    \"LDL\": {\n",
    "        \"units\": \"mg/dL\",\n",
    "        \"normal\": lambda v: v < 100,\n",
    "        \"categories\": [\n",
    "            (100, 129, \"borderline high\"),\n",
    "            (130, 159, \"high\"),\n",
    "            (160, float(\"inf\"), \"very high\"),\n",
    "        ],\n",
    "    },\n",
    "    \"HDL\": {\n",
    "        \"units\": \"mg/dL\",\n",
    "        \"normal\": lambda v: v >= 40,\n",
    "        \"categories\": [\n",
    "            (-float(\"inf\"), 40, \"low\"),\n",
    "        ],\n",
    "    },\n",
    "    \"Triglycerides\": {\n",
    "        \"units\": \"mg/dL\",\n",
    "        \"normal\": lambda v: v < 150,\n",
    "        \"categories\": [\n",
    "            (150, 199, \"borderline high\"),\n",
    "            (200, 499, \"high\"),\n",
    "            (500, float(\"inf\"), \"very high\"),\n",
    "        ],\n",
    "    },\n",
    "    \"A1c\": {\n",
    "        \"units\": \"%\",\n",
    "        \"normal\": lambda v: v < 5.7,\n",
    "        \"categories\": [\n",
    "            (5.7, 6.4, \"prediabetes range\"),\n",
    "            (6.5, float(\"inf\"), \"diabetes range\"),\n",
    "        ],\n",
    "    },\n",
    "    \"Creatinine\": {\n",
    "        \"units\": \"mg/dL\",\n",
    "        \"normal\": lambda v: 0.6 <= v <= 1.3,\n",
    "        \"categories\": [\n",
    "            (-float(\"inf\"), 0.6, \"low\"),\n",
    "            (1.31, float(\"inf\"), \"high\"),\n",
    "        ],\n",
    "    },\n",
    "    \"eGFR\": {\n",
    "        \"units\": \"mL/min/1.73m²\",\n",
    "        \"normal\": lambda v: v >= 90,\n",
    "        \"categories\": [\n",
    "            (60, 89, \"mildly decreased\"),\n",
    "            (45, 59, \"moderately decreased\"),\n",
    "            (30, 44, \"severely decreased\"),\n",
    "            (-float(\"inf\"), 29, \"kidney function very low\"),\n",
    "        ],\n",
    "    },\n",
    "    \"ALT\": {\n",
    "        \"units\": \"U/L\",\n",
    "        \"normal\": lambda v: v <= 40,\n",
    "        \"categories\": [\n",
    "            (41, 79, \"mildly elevated\"),\n",
    "            (80, 149, \"moderately elevated\"),\n",
    "            (150, float(\"inf\"), \"markedly elevated\"),\n",
    "        ],\n",
    "    },\n",
    "    \"AST\": {\n",
    "        \"units\": \"U/L\",\n",
    "        \"normal\": lambda v: v <= 40,\n",
    "        \"categories\": [\n",
    "            (41, 79, \"mildly elevated\"),\n",
    "            (80, 149, \"moderately elevated\"),\n",
    "            (150, float(\"inf\"), \"markedly elevated\"),\n",
    "        ],\n",
    "    },\n",
    "    \"Vitamin_D\": {\n",
    "        \"units\": \"ng/mL\",\n",
    "        \"normal\": lambda v: v >= 30,\n",
    "        \"categories\": [\n",
    "            (20, 29, \"insufficient\"),\n",
    "            (0, 19, \"deficient\"),\n",
    "        ],\n",
    "    },\n",
    "}\n",
    "\n",
    "\n",
    "def range_check(lab, value):\n",
    "    \"\"\"\n",
    "    Returns structured interpretation of a single lab:\n",
    "    {\n",
    "        lab, value, units, flagged, interpretation\n",
    "    }\n",
    "    \"\"\"\n",
    "    rule = LAB_RULES.get(lab)\n",
    "    if rule is None:\n",
    "        return {\n",
    "            \"lab\": lab,\n",
    "            \"value\": value,\n",
    "            \"units\": \"\",\n",
    "            \"flagged\": False,\n",
    "            \"interpretation\": \"unknown lab\",\n",
    "        }\n",
    "\n",
    "    if rule[\"normal\"](value):\n",
    "        return {\n",
    "            \"lab\": lab,\n",
    "            \"value\": value,\n",
    "            \"units\": rule[\"units\"],\n",
    "            \"flagged\": False,\n",
    "            \"interpretation\": \"normal\",\n",
    "        }\n",
    "\n",
    "    for low, high, label in rule[\"categories\"]:\n",
    "        if low <= value <= high:\n",
    "            return {\n",
    "                \"lab\": lab,\n",
    "                \"value\": value,\n",
    "                \"units\": rule[\"units\"],\n",
    "                \"flagged\": True,\n",
    "                \"interpretation\": label,\n",
    "            }\n",
    "\n",
    "    return {\n",
    "        \"lab\": lab,\n",
    "        \"value\": value,\n",
    "        \"units\": rule[\"units\"],\n",
    "        \"flagged\": True,\n",
    "        \"interpretation\": \"abnormal\",\n",
    "    }\n",
    "\n",
    "\n",
    "def severity_points(lab, value):\n",
    "    \"\"\"\n",
    "    Internal helper used by severity_score.\n",
    "    \"\"\"\n",
    "    if lab == \"ALT\":\n",
    "        if value >= 150:\n",
    "            return 4\n",
    "        elif value >= 80:\n",
    "            return 3\n",
    "        elif value > 40:\n",
    "            return 1\n",
    "\n",
    "    if lab == \"AST\":\n",
    "        if value >= 150:\n",
    "            return 4\n",
    "        elif value >= 80:\n",
    "            return 3\n",
    "        elif value > 40:\n",
    "            return 1\n",
    "\n",
    "    if lab == \"A1c\":\n",
    "        if value >= 8.0:\n",
    "            return 3\n",
    "        elif value >= 6.5:\n",
    "            return 2\n",
    "        elif value >= 5.7:\n",
    "            return 1\n",
    "\n",
    "    if lab == \"eGFR\":\n",
    "        if value < 30:\n",
    "            return 4\n",
    "        elif value < 45:\n",
    "            return 3\n",
    "        elif value < 60:\n",
    "            return 2\n",
    "        elif value < 90:\n",
    "            return 1\n",
    "\n",
    "    if lab == \"Creatinine\":\n",
    "        if value > 1.5:\n",
    "            return 2\n",
    "        elif value > 1.3:\n",
    "            return 1\n",
    "\n",
    "    if lab == \"Triglycerides\":\n",
    "        if value >= 500:\n",
    "            return 4\n",
    "        elif value >= 200:\n",
    "            return 2\n",
    "        elif value >= 150:\n",
    "            return 1\n",
    "\n",
    "    if lab == \"LDL\":\n",
    "        if value >= 160:\n",
    "            return 2\n",
    "        elif value >= 130:\n",
    "            return 1\n",
    "        elif value >= 100:\n",
    "            return 0.5\n",
    "\n",
    "    if lab == \"HDL\":\n",
    "        if value < 40:\n",
    "            return 1\n",
    "\n",
    "    if lab == \"Vitamin_D\":\n",
    "        if value < 20:\n",
    "            return 1\n",
    "        elif value < 30:\n",
    "            return 0.5\n",
    "\n",
    "    return 0\n",
    "\n",
    "\n",
    "def severity_score(labs):\n",
    "    \"\"\"\n",
    "    Returns:\n",
    "    {\n",
    "        score: float,\n",
    "        severity: str,\n",
    "        rationale: list[str]\n",
    "    }\n",
    "    \"\"\"\n",
    "    total = 0\n",
    "    rationale = []\n",
    "\n",
    "    for lab, value in labs.items():\n",
    "        pts = severity_points(lab, value)\n",
    "        total += pts\n",
    "        if pts > 0:\n",
    "            rationale.append(f\"{lab} contributed {pts} point(s)\")\n",
    "\n",
    "    \n",
    "    urgent_trigger = (\n",
    "        labs.get(\"ALT\", 0) >= 150\n",
    "        or labs.get(\"AST\", 0) >= 150\n",
    "        or labs.get(\"Triglycerides\", 0) >= 500\n",
    "        or labs.get(\"eGFR\", 999) < 30\n",
    "    )\n",
    "\n",
    "    if urgent_trigger:\n",
    "        severity = \"Urgent follow-up\"\n",
    "        rationale.append(\"Urgent threshold triggered by at least one lab value\")\n",
    "    elif total >= 4:\n",
    "        severity = \"Follow-up recommended\"\n",
    "    else:\n",
    "        severity = \"Routine\"\n",
    "\n",
    "    return {\n",
    "        \"score\": total,\n",
    "        \"severity\": severity,\n",
    "        \"rationale\": rationale,\n",
    "    }\n",
    "\n",
    "\n",
    "def prioritize_findings(flagged_labs):\n",
    "    \"\"\"\n",
    "    Sort flagged labs by importance.\n",
    "    \"\"\"\n",
    "    priority_order = {\n",
    "        \"ALT\": 1,\n",
    "        \"AST\": 2,\n",
    "        \"eGFR\": 3,\n",
    "        \"Creatinine\": 4,\n",
    "        \"A1c\": 5,\n",
    "        \"Triglycerides\": 6,\n",
    "        \"LDL\": 7,\n",
    "        \"HDL\": 8,\n",
    "        \"Vitamin_D\": 9,\n",
    "    }\n",
    "\n",
    "    return sorted(\n",
    "        flagged_labs,\n",
    "        key=lambda x: (\n",
    "            priority_order.get(x[\"lab\"], 99),\n",
    "            -abs(x[\"value\"]) if isinstance(x[\"value\"], (int, float)) else 0,\n",
    "        ),\n",
    "    )\n",
    "\n",
    "\n",
    "def generate_followup_questions(labs, context):\n",
    "    \"\"\"\n",
    "    Produce clarification questions for the physician or patient context.\n",
    "    \"\"\"\n",
    "    questions = []\n",
    "\n",
    "    if labs.get(\"ALT\", 0) > 80 or labs.get(\"AST\", 0) > 80:\n",
    "        questions.append(\n",
    "            \"Has the patient had recent alcohol use, acetaminophen use, viral illness, supplements, or other possible liver stressors?\"\n",
    "        )\n",
    "        if \"dark urine\" in context.get(\"symptoms\", []) or \"nausea\" in context.get(\"symptoms\", []):\n",
    "            questions.append(\n",
    "                \"Given symptoms such as nausea or dark urine, should the patient be contacted sooner for clinical review?\"\n",
    "            )\n",
    "\n",
    "    if labs.get(\"A1c\", 0) >= 6.5:\n",
    "        questions.append(\n",
    "            \"Does the patient have home glucose readings, recent dietary changes, or missed diabetes medication doses?\"\n",
    "        )\n",
    "\n",
    "    if labs.get(\"eGFR\", 999) < 60 or labs.get(\"Creatinine\", 0) > 1.3:\n",
    "        questions.append(\n",
    "            \"Should kidney function be repeated, and are there recent hydration changes, NSAID use, or other possible contributors?\"\n",
    "        )\n",
    "\n",
    "    if labs.get(\"Triglycerides\", 0) >= 200 and not context.get(\"fasting\", False):\n",
    "        questions.append(\n",
    "            \"Triglycerides are elevated on a non-fasting sample; should fasting labs be repeated?\"\n",
    "        )\n",
    "\n",
    "    if labs.get(\"Vitamin_D\", 999) < 20:\n",
    "        questions.append(\n",
    "            \"Would you like to discuss vitamin D replacement or repeat testing at follow-up?\"\n",
    "        )\n",
    "\n",
    "    return questions\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 92,
   "id": "b0639d70",
   "metadata": {},
   "outputs": [],
   "source": [
    "def analyze_case(patient):\n",
    "    labs = patient[\"labs\"]\n",
    "\n",
    "    lab_interpretations = []\n",
    "    flagged = []\n",
    "\n",
    "    for lab, value in labs.items():\n",
    "        result = range_check(lab, value)\n",
    "        lab_interpretations.append(result)\n",
    "        if result[\"flagged\"]:\n",
    "            flagged.append(result)\n",
    "\n",
    "    prioritized = prioritize_findings(flagged)\n",
    "    severity = severity_score(labs)\n",
    "    followup_questions = generate_followup_questions(labs, patient)\n",
    "\n",
    "    audit = {\n",
    "        \"patient_id\": patient[\"patient_id\"],\n",
    "        \"abnormal_labs\": prioritized,\n",
    "        \"severity\": severity[\"severity\"],\n",
    "        \"severity_score\": severity[\"score\"],\n",
    "        \"severity_rationale\": severity[\"rationale\"],\n",
    "        \"followup_questions\": followup_questions,\n",
    "    }\n",
    "\n",
    "    return audit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 93,
   "id": "820d96b0",
   "metadata": {},
   "outputs": [],
   "source": [
    "def build_generation_prompt(patient, audit):\n",
    "    return f\"\"\"\n",
    "You are drafting a clinician-to-patient message for physician review.\n",
    "\n",
    "Write the message as if the physician is speaking directly to the patient.\n",
    "\n",
    "Important safety rules:\n",
    "- Do not diagnose any condition.\n",
    "- Do not say the patient definitely has a disease.\n",
    "- Do not recommend medication changes.\n",
    "- Do not provide dosage instructions.\n",
    "- Do not make definitive clinical conclusions.\n",
    "- Do not speculate beyond the provided lab results and context.\n",
    "- Do not mention internal scoring, tools, or audit logic.\n",
    "- Use cautious language such as:\n",
    "  - \"is outside the usual range\"\n",
    "  - \"would be worth discussing\"\n",
    "  - \"may need follow-up\"\n",
    "  - \"we may want to repeat this test\"\n",
    "  - \"I would like to review these results with you\"\n",
    "\n",
    "Style requirements:\n",
    "- Keep the message clear, brief, and patient-friendly.\n",
    "- Sound professional and calm.\n",
    "- Focus only on the most important abnormal findings.\n",
    "- Do not list every lab unless necessary.\n",
    "- End with an appropriate next-step statement.\n",
    "\n",
    "Severity category: {audit[\"severity\"]}\n",
    "\n",
    "Patient context:\n",
    "- Patient ID: {patient[\"patient_id\"]}\n",
    "- Age: {patient[\"age\"]}\n",
    "- Sex: {patient[\"sex\"]}\n",
    "- Fasting: {patient[\"fasting\"]}\n",
    "- Conditions: {patient[\"conditions\"]}\n",
    "- Medications: {patient[\"medications\"]}\n",
    "- Symptoms: {patient[\"symptoms\"]}\n",
    "\n",
    "Lab results:\n",
    "{json.dumps(patient[\"labs\"], indent=2)}\n",
    "\n",
    "Structured audit:\n",
    "{json.dumps(audit, indent=2)}\n",
    "\n",
    "Instructions by severity:\n",
    "- If severity is \"Routine\":\n",
    "  write a reassuring message, mention that a few results are slightly outside the usual range, and say they can be reviewed at follow-up.\n",
    "- If severity is \"Follow-up recommended\":\n",
    "  mention that several results would be worth discussing and suggest scheduling a follow-up appointment.\n",
    "- If severity is \"Urgent follow-up\":\n",
    "  say that a few findings should be reviewed promptly and advise the patient to contact the office soon for follow-up.\n",
    "\n",
    "Output rules:\n",
    "- Return only the message text.\n",
    "- Do not use bullet points.\n",
    "- Do not use quotation marks around the message.\n",
    "- Do not include placeholders like [Physician Name].\n",
    "- Do not mention possible diagnoses.\n",
    "\n",
    "DO NOT use phrases like:\n",
    "- \"indicates\"\n",
    "- \"suggests disease\"\n",
    "- \"consistent with\"\n",
    "- \"diagnosis\"\n",
    "\"\"\".strip()\n",
    "\n",
    "\n",
    "def generate_draft_message(patient, audit):\n",
    "    prompt = build_generation_prompt(patient, audit)\n",
    "\n",
    "    try:\n",
    "        response = chat(\n",
    "            model=\"llama3.2\",\n",
    "            messages=[\n",
    "                {\n",
    "                    \"role\": \"user\",\n",
    "                    \"content\": prompt\n",
    "                }\n",
    "            ]\n",
    "        )\n",
    "\n",
    "        text = response[\"message\"][\"content\"].strip()\n",
    "\n",
    "        if not text:\n",
    "            return safe_fallback_message(audit)\n",
    "\n",
    "        text = text.strip().strip('\"').strip(\"'\")\n",
    "\n",
    "        if not text:\n",
    "            return safe_fallback_message(audit)\n",
    "\n",
    "        return text\n",
    "\n",
    "    except Exception:\n",
    "        return safe_fallback_message(audit)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "id": "2a4b88d9",
   "metadata": {},
   "outputs": [],
   "source": [
    "def build_safety_prompt(draft_message, patient, audit):\n",
    "    return f\"\"\"\n",
    "You are a healthcare AI safety reviewer.\n",
    "\n",
    "Review the draft clinician-to-patient message for unsafe content.\n",
    "\n",
    "Check for:\n",
    "- diagnostic language\n",
    "- medication advice or treatment changes\n",
    "- dosage instructions\n",
    "- overconfident claims\n",
    "- hallucinated facts not supported by the input\n",
    "- definitive clinical conclusions\n",
    "- statements that go beyond the provided labs and context\n",
    "\n",
    "The message must:\n",
    "- stay cautious\n",
    "- avoid diagnosis\n",
    "- avoid medication changes\n",
    "- avoid telling the patient what condition they have\n",
    "- say that results should be reviewed/discussed with the clinician\n",
    "\n",
    "Patient context:\n",
    "{json.dumps(patient, indent=2)}\n",
    "\n",
    "Audit:\n",
    "{json.dumps(audit, indent=2)}\n",
    "\n",
    "Draft message:\n",
    "\\\"\\\"\\\"\n",
    "{draft_message}\n",
    "\\\"\\\"\\\"\n",
    "\"\"\"\n",
    "\n",
    "def safe_fallback_message(audit):\n",
    "    severity = audit.get(\"severity\", \"Routine\")\n",
    "\n",
    "    if severity == \"Urgent follow-up\":\n",
    "        return (\n",
    "            \"I reviewed your recent lab results and a few results need to be discussed promptly. \"\n",
    "            \"I would like to review these results with you soon and talk about if additional evaluation is needed. \"\n",
    "            \"Please contact our office as soon as possible.\"\n",
    "        )\n",
    "    elif severity == \"Follow-up recommended\":\n",
    "        return (\n",
    "            \"I reviewed your recent lab results and a few findings would be worth discussing. \"\n",
    "            \"I would like to review these results with you and discuss whether follow-up testing may be needed. \"\n",
    "            \"Please schedule a follow-up appointment when convenient.\"\n",
    "        )\n",
    "    else:\n",
    "        return (\n",
    "            \"I reviewed your recent lab results. A few results are slightly outside the usual range, \"\n",
    "            \"and I would like to go over them with you.\"\n",
    "        )\n",
    "\n",
    "\n",
    "def safety_review(draft_message, patient, audit):\n",
    "    prompt = build_safety_prompt(draft_message, patient, audit) + \"\"\"\n",
    "\n",
    "Return valid JSON only.\n",
    "Do not use markdown.\n",
    "Do not include explanation.\n",
    "Format:\n",
    "{\n",
    "  \"safe\": true,\n",
    "  \"issues\": [],\n",
    "  \"revised_message\": \"...\"\n",
    "}\n",
    "\"\"\"\n",
    "\n",
    "    try:\n",
    "        response = chat(\n",
    "            model=\"llama3.2\",\n",
    "            messages=[{\"role\": \"user\", \"content\": prompt}]\n",
    "        )\n",
    "\n",
    "        text = response[\"message\"][\"content\"].strip()\n",
    "\n",
    "        \n",
    "        text = text.replace(\"```json\", \"\").replace(\"```\", \"\").strip()\n",
    "\n",
    "        \n",
    "        match = re.search(r\"\\{[\\s\\S]*?\\}\", text)\n",
    "\n",
    "        if not match:\n",
    "            return {\n",
    "                \"safe\": False,\n",
    "                \"issues\": [\"No JSON returned\"],\n",
    "                \"revised_message\": safe_fallback_message(audit)\n",
    "            }\n",
    "\n",
    "        parsed = json.loads(match.group(0))\n",
    "\n",
    "        if not isinstance(parsed, dict):\n",
    "            raise ValueError(\"Not a dict\")\n",
    "\n",
    "        if \"revised_message\" not in parsed:\n",
    "            raise ValueError(\"Missing key\")\n",
    "\n",
    "        if not parsed[\"revised_message\"].strip():\n",
    "            parsed[\"revised_message\"] = safe_fallback_message(audit)\n",
    "\n",
    "        return parsed\n",
    "\n",
    "    except Exception as e:\n",
    "        return {\n",
    "            \"safe\": False,\n",
    "            \"issues\": [str(e)],\n",
    "            \"revised_message\": safe_fallback_message(audit)\n",
    "        }"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 95,
   "id": "2a7f704a",
   "metadata": {},
   "outputs": [],
   "source": [
    "def append_to_outbox(record, filename=OUTBOX_FILE):\n",
    "    if os.path.exists(filename):\n",
    "        with open(filename, \"r\", encoding=\"utf-8\") as f:\n",
    "            try:\n",
    "                outbox = json.load(f)\n",
    "            except json.JSONDecodeError:\n",
    "                outbox = []\n",
    "    else:\n",
    "        outbox = []\n",
    "\n",
    "    outbox.append(record)\n",
    "\n",
    "    with open(filename, \"w\", encoding=\"utf-8\") as f:\n",
    "        json.dump(outbox, f, indent=2)\n",
    "\n",
    "    return True"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 96,
   "id": "e1d5cb40",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/f4/7j76s88n1l3bhjnz3trgdjs80000gn/T/ipykernel_95649/2085655668.py:10: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).\n",
      "  \"timestamp\": datetime.utcnow().isoformat() + \"Z\",\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "================================================================================\n",
      "Patient: LAB_001\n",
      "Severity: Routine\n",
      "\n",
      "Structured Audit Output:\n",
      "{\n",
      "  \"patient_id\": \"LAB_001\",\n",
      "  \"abnormal_labs\": [\n",
      "    {\n",
      "      \"lab\": \"LDL\",\n",
      "      \"value\": 118,\n",
      "      \"units\": \"mg/dL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"borderline high\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"Vitamin_D\",\n",
      "      \"value\": 16,\n",
      "      \"units\": \"ng/mL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"deficient\"\n",
      "    }\n",
      "  ],\n",
      "  \"severity\": \"Routine\",\n",
      "  \"severity_score\": 1.5,\n",
      "  \"severity_rationale\": [\n",
      "    \"LDL contributed 0.5 point(s)\",\n",
      "    \"Vitamin_D contributed 1 point(s)\"\n",
      "  ],\n",
      "  \"followup_questions\": [\n",
      "    \"Would you like to discuss vitamin D replacement or repeat testing at follow-up?\"\n",
      "  ]\n",
      "}\n",
      "\n",
      "Draft Message:\n",
      "I reviewed your recent lab results. A few results are slightly outside the usual range, and I would like to go over them with you.\n",
      "\n",
      "Safety Review:\n",
      "{\n",
      "  \"safe\": false,\n",
      "  \"issues\": [\n",
      "    \"Diagnostic language: 'slightly above the usual range' might imply a diagnosis of high cholesterol.\",\n",
      "    \"Medication advice or treatment changes: Vitamin D replacement is suggested without a clear indication or prescription from the clinician.\",\n",
      "    \"Dosage instructions: No dosage information for Vitamin D replacement is provided.\",\n",
      "    \"Overconfident claims: The message states 'would be worth discussing further' which might imply that the patient has high cholesterol.\",\n",
      "    \"Hallucinated facts not supported by the input: Repeat testing at follow-up is suggested without clear justification or recommendation from the clinician.\",\n",
      "    \"Definitive clinical conclusions: The message implies a diagnosis and treatment plan without a review with the clinician.\",\n",
      "    \"Statements that go beyond the provided labs and context: The message suggests Vitamin D replacement based on low levels, which might not be a routine recommendation.\"\n",
      "  ],\n",
      "  \"revised_message\": \"I reviewed your recent lab results. A few results are slightly outside the usual range, and I would like to go over them with you.\"\n",
      "}\n",
      "\n",
      "Saved to outbox.json: True\n",
      "================================================================================\n",
      "Patient: LAB_002\n",
      "Severity: Follow-up recommended\n",
      "\n",
      "Structured Audit Output:\n",
      "{\n",
      "  \"patient_id\": \"LAB_002\",\n",
      "  \"abnormal_labs\": [\n",
      "    {\n",
      "      \"lab\": \"ALT\",\n",
      "      \"value\": 46,\n",
      "      \"units\": \"U/L\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"mildly elevated\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"A1c\",\n",
      "      \"value\": 6.0,\n",
      "      \"units\": \"%\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"prediabetes range\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"Triglycerides\",\n",
      "      \"value\": 286,\n",
      "      \"units\": \"mg/dL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"high\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"LDL\",\n",
      "      \"value\": 154,\n",
      "      \"units\": \"mg/dL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"high\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"HDL\",\n",
      "      \"value\": 38,\n",
      "      \"units\": \"mg/dL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"low\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"Vitamin_D\",\n",
      "      \"value\": 24,\n",
      "      \"units\": \"ng/mL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"insufficient\"\n",
      "    }\n",
      "  ],\n",
      "  \"severity\": \"Follow-up recommended\",\n",
      "  \"severity_score\": 6.5,\n",
      "  \"severity_rationale\": [\n",
      "    \"LDL contributed 1 point(s)\",\n",
      "    \"HDL contributed 1 point(s)\",\n",
      "    \"Triglycerides contributed 2 point(s)\",\n",
      "    \"A1c contributed 1 point(s)\",\n",
      "    \"ALT contributed 1 point(s)\",\n",
      "    \"Vitamin_D contributed 0.5 point(s)\"\n",
      "  ],\n",
      "  \"followup_questions\": [\n",
      "    \"Triglycerides are elevated on a non-fasting sample; should fasting labs be repeated?\"\n",
      "  ]\n",
      "}\n",
      "\n",
      "Draft Message:\n",
      "I reviewed your recent lab results and a few findings would be worth discussing. I would like to review these results with you and discuss whether follow-up testing may be needed. Please schedule a follow-up appointment when convenient.\n",
      "\n",
      "Safety Review:\n",
      "{\n",
      "  \"safe\": false,\n",
      "  \"issues\": [\n",
      "    \"No JSON returned\"\n",
      "  ],\n",
      "  \"revised_message\": \"I reviewed your recent lab results and a few findings would be worth discussing. I would like to review these results with you and discuss whether follow-up testing may be needed. Please schedule a follow-up appointment when convenient.\"\n",
      "}\n",
      "\n",
      "Saved to outbox.json: True\n",
      "================================================================================\n",
      "Patient: LAB_003\n",
      "Severity: Follow-up recommended\n",
      "\n",
      "Structured Audit Output:\n",
      "{\n",
      "  \"patient_id\": \"LAB_003\",\n",
      "  \"abnormal_labs\": [\n",
      "    {\n",
      "      \"lab\": \"eGFR\",\n",
      "      \"value\": 52,\n",
      "      \"units\": \"mL/min/1.73m\\u00b2\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"moderately decreased\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"Creatinine\",\n",
      "      \"value\": 1.5,\n",
      "      \"units\": \"mg/dL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"high\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"A1c\",\n",
      "      \"value\": 8.1,\n",
      "      \"units\": \"%\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"diabetes range\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"Triglycerides\",\n",
      "      \"value\": 248,\n",
      "      \"units\": \"mg/dL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"high\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"HDL\",\n",
      "      \"value\": 36,\n",
      "      \"units\": \"mg/dL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"low\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"Vitamin_D\",\n",
      "      \"value\": 27,\n",
      "      \"units\": \"ng/mL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"insufficient\"\n",
      "    }\n",
      "  ],\n",
      "  \"severity\": \"Follow-up recommended\",\n",
      "  \"severity_score\": 9.5,\n",
      "  \"severity_rationale\": [\n",
      "    \"HDL contributed 1 point(s)\",\n",
      "    \"Triglycerides contributed 2 point(s)\",\n",
      "    \"A1c contributed 3 point(s)\",\n",
      "    \"Creatinine contributed 1 point(s)\",\n",
      "    \"eGFR contributed 2 point(s)\",\n",
      "    \"Vitamin_D contributed 0.5 point(s)\"\n",
      "  ],\n",
      "  \"followup_questions\": [\n",
      "    \"Does the patient have home glucose readings, recent dietary changes, or missed diabetes medication doses?\",\n",
      "    \"Should kidney function be repeated, and are there recent hydration changes, NSAID use, or other possible contributors?\"\n",
      "  ]\n",
      "}\n",
      "\n",
      "Draft Message:\n",
      "I reviewed your recent lab results and a few findings would be worth discussing. I would like to review these results with you and discuss whether follow-up testing may be needed. Please schedule a follow-up appointment when convenient.\n",
      "\n",
      "Safety Review:\n",
      "{\n",
      "  \"safe\": false,\n",
      "  \"issues\": [\n",
      "    \"No JSON returned\"\n",
      "  ],\n",
      "  \"revised_message\": \"I reviewed your recent lab results and a few findings would be worth discussing. I would like to review these results with you and discuss whether follow-up testing may be needed. Please schedule a follow-up appointment when convenient.\"\n",
      "}\n",
      "\n",
      "Saved to outbox.json: True\n",
      "================================================================================\n",
      "Patient: LAB_004\n",
      "Severity: Urgent follow-up\n",
      "\n",
      "Structured Audit Output:\n",
      "{\n",
      "  \"patient_id\": \"LAB_004\",\n",
      "  \"abnormal_labs\": [\n",
      "    {\n",
      "      \"lab\": \"ALT\",\n",
      "      \"value\": 184,\n",
      "      \"units\": \"U/L\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"markedly elevated\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"AST\",\n",
      "      \"value\": 162,\n",
      "      \"units\": \"U/L\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"markedly elevated\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"LDL\",\n",
      "      \"value\": 102,\n",
      "      \"units\": \"mg/dL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"borderline high\"\n",
      "    }\n",
      "  ],\n",
      "  \"severity\": \"Urgent follow-up\",\n",
      "  \"severity_score\": 8.5,\n",
      "  \"severity_rationale\": [\n",
      "    \"LDL contributed 0.5 point(s)\",\n",
      "    \"ALT contributed 4 point(s)\",\n",
      "    \"AST contributed 4 point(s)\",\n",
      "    \"Urgent threshold triggered by at least one lab value\"\n",
      "  ],\n",
      "  \"followup_questions\": [\n",
      "    \"Has the patient had recent alcohol use, acetaminophen use, viral illness, supplements, or other possible liver stressors?\",\n",
      "    \"Given symptoms such as nausea or dark urine, should the patient be contacted sooner for clinical review?\"\n",
      "  ]\n",
      "}\n",
      "\n",
      "Draft Message:\n",
      "I reviewed your recent lab results and a few results need to be discussed promptly. I would like to review these results with you soon and talk about if additional evaluation is needed. Please contact our office as soon as possible.\n",
      "\n",
      "Safety Review:\n",
      "{\n",
      "  \"safe\": false,\n",
      "  \"issues\": [\n",
      "    \"Diagnostic language: 'notably elevated' and 'may need follow-up'\",\n",
      "    \"Medication advice or treatment changes: 'repeat this test'\"\n",
      "  ],\n",
      "  \"revised_message\": \"I reviewed your recent lab results and a few results need to be discussed promptly. I would like to review these results with you soon and talk about if additional evaluation is needed. Please contact our office as soon as possible.\"\n",
      "}\n",
      "\n",
      "Saved to outbox.json: True\n",
      "================================================================================\n",
      "Patient: LAB_005\n",
      "Severity: Follow-up recommended\n",
      "\n",
      "Structured Audit Output:\n",
      "{\n",
      "  \"patient_id\": \"LAB_005\",\n",
      "  \"abnormal_labs\": [\n",
      "    {\n",
      "      \"lab\": \"ALT\",\n",
      "      \"value\": 96,\n",
      "      \"units\": \"U/L\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"moderately elevated\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"AST\",\n",
      "      \"value\": 82,\n",
      "      \"units\": \"U/L\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"moderately elevated\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"eGFR\",\n",
      "      \"value\": 68,\n",
      "      \"units\": \"mL/min/1.73m\\u00b2\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"mildly decreased\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"A1c\",\n",
      "      \"value\": 6.7,\n",
      "      \"units\": \"%\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"diabetes range\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"Triglycerides\",\n",
      "      \"value\": 342,\n",
      "      \"units\": \"mg/dL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"high\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"LDL\",\n",
      "      \"value\": 172,\n",
      "      \"units\": \"mg/dL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"very high\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"HDL\",\n",
      "      \"value\": 34,\n",
      "      \"units\": \"mg/dL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"low\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"Vitamin_D\",\n",
      "      \"value\": 18,\n",
      "      \"units\": \"ng/mL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"deficient\"\n",
      "    }\n",
      "  ],\n",
      "  \"severity\": \"Follow-up recommended\",\n",
      "  \"severity_score\": 15,\n",
      "  \"severity_rationale\": [\n",
      "    \"LDL contributed 2 point(s)\",\n",
      "    \"HDL contributed 1 point(s)\",\n",
      "    \"Triglycerides contributed 2 point(s)\",\n",
      "    \"A1c contributed 2 point(s)\",\n",
      "    \"eGFR contributed 1 point(s)\",\n",
      "    \"ALT contributed 3 point(s)\",\n",
      "    \"AST contributed 3 point(s)\",\n",
      "    \"Vitamin_D contributed 1 point(s)\"\n",
      "  ],\n",
      "  \"followup_questions\": [\n",
      "    \"Has the patient had recent alcohol use, acetaminophen use, viral illness, supplements, or other possible liver stressors?\",\n",
      "    \"Does the patient have home glucose readings, recent dietary changes, or missed diabetes medication doses?\",\n",
      "    \"Would you like to discuss vitamin D replacement or repeat testing at follow-up?\"\n",
      "  ]\n",
      "}\n",
      "\n",
      "Draft Message:\n",
      "Hello, I'd like to review your recent lab results with you. You have several abnormal values that require discussion. Would you be available to schedule a follow-up appointment? Please review the results with your clinician before scheduling.\n",
      "\n",
      "Safety Review:\n",
      "{\n",
      "  \"safe\": false,\n",
      "  \"issues\": [\n",
      "    \"The message implies a diagnosis based on lab results: 'Your liver enzymes and cholesterol levels are elevated'.\",\n",
      "    \"The message makes medication changes suggestion: 'We may want to repeat some tests at follow-up to confirm these findings and discuss any potential concerns.'\",\n",
      "    \"The message tells the patient what condition they have: 'You have high cholesterol, low vitamin D, and mildly decreased eGFR'.\",\n",
      "    \"The message does not review labs with the clinician: 'We may want to repeat some tests at follow-up to confirm these findings'\"\n",
      "  ],\n",
      "  \"revised_message\": \"Hello, I'd like to review your recent lab results with you. You have several abnormal values that require discussion. Would you be available to schedule a follow-up appointment? Please review the results with your clinician before scheduling.\"\n",
      "}\n",
      "\n",
      "Saved to outbox.json: True\n",
      "================================================================================\n",
      "Patient: LAB_006\n",
      "Severity: Routine\n",
      "\n",
      "Structured Audit Output:\n",
      "{\n",
      "  \"patient_id\": \"LAB_006\",\n",
      "  \"abnormal_labs\": [\n",
      "    {\n",
      "      \"lab\": \"eGFR\",\n",
      "      \"value\": 66,\n",
      "      \"units\": \"mL/min/1.73m\\u00b2\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"mildly decreased\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"Creatinine\",\n",
      "      \"value\": 1.4,\n",
      "      \"units\": \"mg/dL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"high\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"Vitamin_D\",\n",
      "      \"value\": 29,\n",
      "      \"units\": \"ng/mL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"insufficient\"\n",
      "    }\n",
      "  ],\n",
      "  \"severity\": \"Routine\",\n",
      "  \"severity_score\": 2.5,\n",
      "  \"severity_rationale\": [\n",
      "    \"Creatinine contributed 1 point(s)\",\n",
      "    \"eGFR contributed 1 point(s)\",\n",
      "    \"Vitamin_D contributed 0.5 point(s)\"\n",
      "  ],\n",
      "  \"followup_questions\": [\n",
      "    \"Should kidney function be repeated, and are there recent hydration changes, NSAID use, or other possible contributors?\"\n",
      "  ]\n",
      "}\n",
      "\n",
      "Draft Message:\n",
      "I reviewed your recent lab results. A few results are slightly outside the usual range, and I would like to go over them with you.\n",
      "\n",
      "Safety Review:\n",
      "{\n",
      "  \"safe\": false,\n",
      "  \"issues\": [\n",
      "    \"Expecting ',' delimiter: line 10 column 24 (char 731)\"\n",
      "  ],\n",
      "  \"revised_message\": \"I reviewed your recent lab results. A few results are slightly outside the usual range, and I would like to go over them with you.\"\n",
      "}\n",
      "\n",
      "Saved to outbox.json: True\n",
      "================================================================================\n",
      "Patient: LAB_007\n",
      "Severity: Follow-up recommended\n",
      "\n",
      "Structured Audit Output:\n",
      "{\n",
      "  \"patient_id\": \"LAB_007\",\n",
      "  \"abnormal_labs\": [\n",
      "    {\n",
      "      \"lab\": \"eGFR\",\n",
      "      \"value\": 82,\n",
      "      \"units\": \"mL/min/1.73m\\u00b2\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"mildly decreased\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"A1c\",\n",
      "      \"value\": 7.2,\n",
      "      \"units\": \"%\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"diabetes range\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"Triglycerides\",\n",
      "      \"value\": 198,\n",
      "      \"units\": \"mg/dL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"borderline high\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"Vitamin_D\",\n",
      "      \"value\": 22,\n",
      "      \"units\": \"ng/mL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"insufficient\"\n",
      "    }\n",
      "  ],\n",
      "  \"severity\": \"Follow-up recommended\",\n",
      "  \"severity_score\": 4.5,\n",
      "  \"severity_rationale\": [\n",
      "    \"Triglycerides contributed 1 point(s)\",\n",
      "    \"A1c contributed 2 point(s)\",\n",
      "    \"eGFR contributed 1 point(s)\",\n",
      "    \"Vitamin_D contributed 0.5 point(s)\"\n",
      "  ],\n",
      "  \"followup_questions\": [\n",
      "    \"Does the patient have home glucose readings, recent dietary changes, or missed diabetes medication doses?\"\n",
      "  ]\n",
      "}\n",
      "\n",
      "Draft Message:\n",
      "I reviewed your recent lab results and a few findings would be worth discussing. I would like to review these results with you and discuss whether follow-up testing may be needed. Please schedule a follow-up appointment when convenient.\n",
      "\n",
      "Safety Review:\n",
      "{\n",
      "  \"safe\": false,\n",
      "  \"issues\": [\n",
      "    \"Diagnostic language: 'mildly decreased' eGFR value may be too specific for a lab result\",\n",
      "    \"Medication advice or treatment changes: No, but the patient has type 2 diabetes and takes metformin.\",\n",
      "    \"Dosage instructions: No\",\n",
      "    \"Overconfident claims: The message is cautious but does imply that the results require further evaluation without referencing clinical guidelines.\",\n",
      "    \"Hallucinated facts not supported by the input: There are no hallucinated facts in this message.\",\n",
      "    \"Definitive clinical conclusions: The message implies a definitive conclusion about the patient's condition based on lab results without consulting with the clinician.\",\n",
      "    \"Statements that go beyond the provided labs and context: The message mentions 'recent dietary changes' which may not be part of the patient's medical history.\"\n",
      "  ],\n",
      "  \"revised_message\": \"I reviewed your recent lab results and a few findings would be worth discussing. I would like to review these results with you and discuss whether follow-up testing may be needed. Please schedule a follow-up appointment when convenient.\"\n",
      "}\n",
      "\n",
      "Saved to outbox.json: True\n",
      "================================================================================\n",
      "Patient: LAB_008\n",
      "Severity: Routine\n",
      "\n",
      "Structured Audit Output:\n",
      "{\n",
      "  \"patient_id\": \"LAB_008\",\n",
      "  \"abnormal_labs\": [\n",
      "    {\n",
      "      \"lab\": \"ALT\",\n",
      "      \"value\": 74,\n",
      "      \"units\": \"U/L\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"mildly elevated\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"AST\",\n",
      "      \"value\": 79,\n",
      "      \"units\": \"U/L\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"mildly elevated\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"A1c\",\n",
      "      \"value\": 5.8,\n",
      "      \"units\": \"%\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"prediabetes range\"\n",
      "    },\n",
      "    {\n",
      "      \"lab\": \"Vitamin_D\",\n",
      "      \"value\": 26,\n",
      "      \"units\": \"ng/mL\",\n",
      "      \"flagged\": true,\n",
      "      \"interpretation\": \"insufficient\"\n",
      "    }\n",
      "  ],\n",
      "  \"severity\": \"Routine\",\n",
      "  \"severity_score\": 3.5,\n",
      "  \"severity_rationale\": [\n",
      "    \"A1c contributed 1 point(s)\",\n",
      "    \"ALT contributed 1 point(s)\",\n",
      "    \"AST contributed 1 point(s)\",\n",
      "    \"Vitamin_D contributed 0.5 point(s)\"\n",
      "  ],\n",
      "  \"followup_questions\": []\n",
      "}\n",
      "\n",
      "Draft Message:\n",
      "I reviewed your recent lab results. A few results are slightly outside the usual range, and I would like to go over them with you.\n",
      "\n",
      "Safety Review:\n",
      "{\n",
      "  \"safe\": false,\n",
      "  \"issues\": [\n",
      "    \"No JSON returned\"\n",
      "  ],\n",
      "  \"revised_message\": \"I reviewed your recent lab results. A few results are slightly outside the usual range, and I would like to go over them with you.\"\n",
      "}\n",
      "\n",
      "Saved to outbox.json: True\n"
     ]
    }
   ],
   "source": [
    "def process_patient_case(patient):\n",
    "    audit = analyze_case(patient)\n",
    "    draft = generate_draft_message(patient, audit)\n",
    "    safety = safety_review(draft, patient, audit)\n",
    "\n",
    "    final_message = safety[\"revised_message\"]\n",
    "\n",
    "    outbox_record = {\n",
    "        \"patient_id\": patient[\"patient_id\"],\n",
    "        \"timestamp\": datetime.utcnow().isoformat() + \"Z\",\n",
    "        \"severity\": audit[\"severity\"],\n",
    "        \"draft_message\": final_message,\n",
    "        \"safety\": {\n",
    "            \"safe\": safety[\"safe\"],\n",
    "            \"issues\": safety[\"issues\"],\n",
    "        },\n",
    "        \"audit\": audit,\n",
    "    }\n",
    "\n",
    "    saved = append_to_outbox(outbox_record)\n",
    "\n",
    "    return {\n",
    "        \"patient_id\": patient[\"patient_id\"],\n",
    "        \"audit\": audit,\n",
    "        \"draft_message\": final_message,\n",
    "        \"safety_review\": safety,\n",
    "        \"saved_to_outbox\": saved,\n",
    "    }\n",
    "\n",
    "\n",
    "def main():\n",
    "\n",
    "    with open(INPUT_FILE, \"r\", encoding=\"utf-8\") as f:\n",
    "        patient_cases = json.load(f)\n",
    "\n",
    "    all_outputs = []\n",
    "\n",
    "    for patient in patient_cases:\n",
    "        result = process_patient_case(patient)\n",
    "        all_outputs.append(result)\n",
    "\n",
    "        print(\"=\" * 80)\n",
    "        print(f\"Patient: {result['patient_id']}\")\n",
    "        print(f\"Severity: {result['audit']['severity']}\")\n",
    "        print(\"\\nStructured Audit Output:\")\n",
    "        print(json.dumps(result[\"audit\"], indent=2))\n",
    "        print(\"\\nDraft Message:\")\n",
    "        print(result[\"draft_message\"])\n",
    "        print(\"\\nSafety Review:\")\n",
    "        print(json.dumps(result[\"safety_review\"], indent=2))\n",
    "        print(f\"\\nSaved to outbox.json: {result['saved_to_outbox']}\")\n",
    "\n",
    "    return all_outputs\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ydata",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
